apiVersion: "v1"
kind: "Secret"
metadata:
  namespace: 'kube-system'
  name: 'hcloud'
type: Opaque
data:
  network: "{{ network_b64 }}"
  token: "{{ token_b64 }}"
{% if robot_credentials_enabled %}
  robot-user: "{{ robot_user_b64 }}"
  robot-password: "{{ robot_password_b64 }}"
{% endif %}
